"""
verify_addition_chains.py

This script verifies the exhaustive-search part of the addition-chain
optimality claims used in the Toom-4 interpolation schedule.

The script searches strictly increasing addition chains generated from 1.
For each prescribed target set, it finds the smallest depth at which
all targets appear in a chain.

Here, the depth is the number of additions.
Thus, a chain of depth r has length r+1.
"""


def next_chains(chain):
    """
    Generate all one-step extensions of a strictly increasing addition chain.

    Given a chain (1 = a_0, a_1, ..., a_r), this function appends one new
    element a_i + a_j, where 0 <= i <= j <= r, provided that the new element
    is larger than the current largest element.

    Parameters
    ----------
    chain : tuple[int]
        A strictly increasing addition chain.

    Returns
    -------
    list[tuple[int]]
        All one-step extensions of the input chain.
    """
    new_chains = []
    last = chain[-1]

    for i in range(len(chain)):
        for j in range(i, len(chain)):
            n = chain[i] + chain[j]
            if n > last:
                new_chains.append(chain + (n,))

    return new_chains


def generate_chains(max_depth):
    """
    Generate all strictly increasing addition chains up to max_depth.

    The returned list is indexed by depth.  Here, depth means the number
    of additions.  Thus, chains_by_depth[r] consists of chains of length r+1.

    Parameters
    ----------
    max_depth : int
        Maximum number of additions.

    Returns
    -------
    list[list[tuple[int]]]
        chains_by_depth[r] is the list of all chains of depth r.
    """
    chains_by_depth = [[(1,)]]

    for depth in range(max_depth):
        next_level = []
        seen = set()

        for chain in chains_by_depth[depth]:
            for new_chain in next_chains(chain):
                if new_chain not in seen:
                    seen.add(new_chain)
                    next_level.append(new_chain)

        chains_by_depth.append(next_level)
        print(f"generated depth {depth + 1}: {len(next_level)} chains")

    return chains_by_depth


def find_chains_containing(chains_by_depth, targets, max_depth=None):
    """
    Find all chains containing a prescribed target set.

    Parameters
    ----------
    chains_by_depth : list[list[tuple[int]]]
        Addition chains generated by generate_chains.
    targets : set[int]
        Target integers that must be contained in the chain.
    max_depth : int or None
        Maximum depth to search.  If None, all generated depths are searched.

    Returns
    -------
    list[tuple[int, tuple[int]]]
        Pairs (depth, chain) such that chain contains all targets.
    """
    targets = set(targets)

    if max_depth is None:
        max_depth = len(chains_by_depth) - 1

    hits = []
    for depth in range(max_depth + 1):
        for chain in chains_by_depth[depth]:
            if targets <= set(chain):
                hits.append((depth, chain))

    return hits


def print_first_hits(chains_by_depth, label, targets, max_depth=None, max_print=50):
    """
    Print the chains of minimal depth containing the prescribed target set.

    Parameters
    ----------
    chains_by_depth : list[list[tuple[int]]]
        Addition chains generated by generate_chains.
    label : str
        Label used in the printed output.
    targets : set[int]
        Target integers that must be contained in the chain.
    max_depth : int or None
        Maximum depth to search.
    max_print : int or None
        Maximum number of minimal chains to print.  If None, print all.
    """
    hits = find_chains_containing(chains_by_depth, targets, max_depth)

    print("-" * 60)
    print(label)
    print(f"targets = {sorted(targets)}")

    if not hits:
        print("No chain found up to the specified depth.")
        return

    min_depth = min(depth for depth, _ in hits)
    first_hits = [chain for depth, chain in hits if depth == min_depth]

    print(f"minimal depth found = {min_depth}")
    print(f"number of minimal chains found = {len(first_hits)}")

    chains_to_print = first_hits if max_print is None else first_hits[:max_print]
    for chain in chains_to_print:
        print(chain)

    if max_print is not None and len(first_hits) > max_print:
        print(f"... {len(first_hits) - max_print} further chains omitted.")


def main():
    max_depth = 8
    chains_by_depth = generate_chains(max_depth)

    target_sets = {
        "H(0)": {10, 30, 40, 50},
        "H(1)": {10, 20, 70},
        "H(-1)": {5, 20, 60, 80},
        "H(2)": {5, 20, 30, 35},
        "H(-2)": {5, 6},
        "H(3)": {4, 5},
        "H(infinity), partial check": {120},
    }

    for label, targets in target_sets.items():
        print_first_hits(
            chains_by_depth,
            label,
            targets,
            max_print=None,
        )


if __name__ == "__main__":
    main()